// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchFunnyClips.Models;

namespace WatchFunnyClips.Migrations
{
    [DbContext(typeof(WatchFunnyClipContext))]
    [Migration("20191212122007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("GenreClips", b =>
                {
                    b.Property<int>("GenreClipsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreClipsId");

                    b.ToTable("GenreClips");
                });

            modelBuilder.Entity("WatchFunnyClips.Models.Clip", b =>
                {
                    b.Property<int>("ClipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreClipsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ClipId");

                    b.HasIndex("GenreClipsId");

                    b.ToTable("Clip");
                });

            modelBuilder.Entity("WatchFunnyClips.Models.Clip", b =>
                {
                    b.HasOne("GenreClips", "GenreClips")
                        .WithMany("Clips")
                        .HasForeignKey("GenreClipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
